### ISSUE TITLE
Evaluation Performance

### ISSUE THREAD

**Issue by rlax59us** [bytedance/piano_transcription#30]
Hi,

Thanks for sharing your work.

When I use the pre-trained model checkpoint from your repo(https://github.com/qiuqiangkong/piano_transcription_inference), 
I can't get the performance of the original paper's score.
![capture](https://github.com/bytedance/piano_transcription/assets/56262962/741b4380-7f20-4260-ad69-876d390a3bc7)

I set the arguments like below.

![setting](https://github.com/bytedance/piano_transcription/assets/56262962/5d6713ed-08df-434a-876c-59542de1fd02)

Much lower performance results were obtained.

Can I get your paper's score with this source code? or do I need to edit something? 
(https://github.com/bytedance/piano_transcription/blob/master/pytorch/calculate_score_for_paper.py)

Thank you.

**Comment by rlax59us** [comment]
Oh, it's right that the performance comes out well. Thank you.

**Comment by guozixunnicolas** [comment]
Hey, I encountered the same problem. May I know what have you done to achieve the same performance results from the paper?

**Comment by rlax59us** [comment]
Hi,
If you check closely the given evaluation code, they use mir_eval.transcription.precision_recall_f1_overlap for the Note F1-score.
However, it is for the Note w/ Offset F1-score, not the Note F1-score.
If you want to get Note F1-score, you should use mir_eval.transcription.onset_precision_recall_f1.
(Please refer to the following link: https://github.com/craffel/mir_eval/blob/main/mir_eval/transcription.py)

**Comment by guozixunnicolas** [comment]
Thank you very much!
